events {}

http {

    server {
        #SSL / TLS config
        listen 443 ssl;
        
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

        #root, index, server_name
        root /var/www/html;
        server_name rcochran.42.fr;
        index index.php index.html index.htm;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            #include fastcgi_params;
            include snippets/fastcgi-php.conf;
            fastcgi_pass wordpress:9000; # communication docker interne
            #fastcgi_index index.php;
            #fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}