services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env.local
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env.local
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception

  nginx:
    build: requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
      #- "80:80"
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: always
    networks:
      - inception
    ports:
      - "8080:8080"

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: always
    networks:
      - inception

  static-site:
    build: ./requirements/bonus/static-site
    container_name: static-site
    restart: always
    networks:
      - inception
    ports:
    - "8081:80"

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception:
    driver: bridge