anonymous_enable=NO
local_enable=YES
write_enable=YES

chroot_local_user=YES
allow_writeable_chroot=YES
local_root=/var/www/wordpress/wp-content/uploads

ftpd_banner=Inception FTP

listen=YES
listen_port=21
listen_address=0.0.0.0
seccomp_sandbox=NO

# Passive mod, used for upload
pasv_enable=YES
pasv_min_port=10000
pasv_max_port=10010

userlist_enable=YES
userlist_file=/etc/vsftpd.userlist
userlist_deny=NO

# used by fail2ban
xferlog_enable=YES
xferlog_file=/var/log/vsftpd/xferlog
log_ftp_protocol=YES

dual_log_enable=YES
vsftpd_log_file=/var/log/vsftpd/vsftpd.log